Repository EntryDSM/Raise-Percent, pull requests merged in 2022-02, with the labels that each got.

#144 🔀 :: (#143) show notice detalis
  src/main/java/kr/hs/entrydsm/raisepercent/domain/notice/presentation/NoticeController.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/notice/presentation/dto/response/NoticeDetailsResponse.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/notice/service/ShowNoticeDetailsService.java
  src/main/java/kr/hs/entrydsm/raisepercent/global/error/exception/ErrorCode.java
  src/main/java/kr/hs/entrydsm/raisepercent/global/exception/NoticeNotFoundException.java
  src/test/java/kr/hs/entrydsm/raisepercent/domain/notice/service/ShowNoticeDetailsServiceTest.java
Labels: 기능 추가

#154 🔀 :: (#153) create tag
  src/main/java/kr/hs/entrydsm/raisepercent/domain/tag/domain/repositories/TagRepository.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/tag/presentation/TagController.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/tag/presentation/dto/request/CreateTagRequest.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/tag/service/CreateTagService.java
  src/main/java/kr/hs/entrydsm/raisepercent/global/config/SecurityConfig.java
  src/test/java/kr/hs/entrydsm/raisepercent/domain/tag/service/CreateTagServiceTest.java
Labels: 기능 추가

#157 🔀 :: (#156) delete tag
  src/main/java/kr/hs/entrydsm/raisepercent/domain/tag/presentation/TagController.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/tag/service/DeleteTagService.java
  src/main/java/kr/hs/entrydsm/raisepercent/global/config/SecurityConfig.java
  src/test/java/kr/hs/entrydsm/raisepercent/domain/tag/service/DeleteTagServiceTest.java
Labels: 기능 추가

#149 🔀 :: (#105) 문서 수정 api
  src/main/java/kr/hs/entrydsm/raisepercent/domain/document/domain/Document.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/document/domain/repositories/LocalDocumentRepository.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/document/domain/types/DocumentType.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/document/presentation/DocumentController.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/document/presentation/dto/request/CreateDocumentRequest.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/document/presentation/dto/request/UpdateDocumentRequest.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/document/service/CreateDocumentService.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/document/service/UpdateDocumentService.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/notification/domain/Notification.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/notification/domain/facade/NotificationFacade.java
  src/main/java/kr/hs/entrydsm/raisepercent/global/config/SecurityConfig.java
  src/test/java/kr/hs/entrydsm/raisepercent/domain/document/domain/DocumentTest.java
  src/test/java/kr/hs/entrydsm/raisepercent/domain/document/service/CreateDocumentServiceTest.java
  src/test/java/kr/hs/entrydsm/raisepercent/domain/document/service/UpdateDocumentServiceTest.java
  src/test/java/kr/hs/entrydsm/raisepercent/domain/notification/domain/NotificationTest.java
  src/test/java/kr/hs/entrydsm/raisepercent/domain/notification/domain/facade/NotificationFacadeTest.java
Labels: 기능 추가

#152 🔀 :: (#150) 문서 제출 api
  src/main/java/kr/hs/entrydsm/raisepercent/domain/document/domain/repositories/LocalDocumentRepository.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/document/presentation/DocumentController.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/document/service/SubmitDocumentService.java
  src/main/java/kr/hs/entrydsm/raisepercent/global/config/SecurityConfig.java
  src/test/java/kr/hs/entrydsm/raisepercent/domain/document/service/SubmitDocumentServiceTest.java
  src/test/java/kr/hs/entrydsm/raisepercent/domain/document/service/UpdateDocumentServiceTest.java
Labels: 기능 추가

#165 🔀 :: (#163) 공개문서 삭제 api
  src/main/java/kr/hs/entrydsm/raisepercent/domain/document/domain/repositories/PublicDocumentRepository.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/document/presentation/DocumentController.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/document/service/DeletePublicDocumentService.java
  src/main/java/kr/hs/entrydsm/raisepercent/global/config/SecurityConfig.java
  src/test/java/kr/hs/entrydsm/raisepercent/domain/document/service/DeletePublicDocumentServiceTest.java
Labels: 기능 추가

#168 🔀 :: (#166) 토큰 발급 로직 리팩토링
  src/main/java/kr/hs/entrydsm/raisepercent/domain/teacher/service/GoogleAuthService.java
  src/main/java/kr/hs/entrydsm/raisepercent/global/facade/AuthFacade.java
  src/main/java/kr/hs/entrydsm/raisepercent/global/security/auth/AuthDetailsService.java
  src/main/java/kr/hs/entrydsm/raisepercent/global/security/jwt/JwtTokenProvider.java
  src/main/java/kr/hs/entrydsm/raisepercent/global/security/jwt/type/TokenRole.java
  src/test/java/kr/hs/entrydsm/raisepercent/domain/teacher/service/GoogleAuthServiceTest.java
  src/test/java/kr/hs/entrydsm/raisepercent/global/facade/AuthFacadeTest.java
  src/test/java/kr/hs/entrydsm/raisepercent/global/security/auth/AuthDetailsServiceTest.java
  src/test/java/kr/hs/entrydsm/raisepercent/global/security/jwt/JwtTokenProviderTest.java
Labels: 리팩토링

#172 🔀 :: (#171) JwtTokenFilter 적용
  src/main/java/kr/hs/entrydsm/raisepercent/global/config/FilterConfig.java
  src/main/java/kr/hs/entrydsm/raisepercent/global/config/SecurityConfig.java
Labels: 기능 추가

#155 🔀 :: (#133) 인사담당자 로그인 링크 가져오기
  src/main/java/kr/hs/entrydsm/raisepercent/domain/hr/facade/HrFacade.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/hr/presentation/HrController.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/teacher/presentation/TeacherController.java
  src/main/java/kr/hs/entrydsm/raisepercent/global/util/auth/service/QueryGoogleAuthLinkService.java
  src/test/java/kr/hs/entrydsm/raisepercent/domain/hr/facade/HrFacadeTest.java
  src/test/java/kr/hs/entrydsm/raisepercent/domain/teacher/service/QueryGoogleAuthLinkServiceTest.java
Labels: 기능 추가

#170 🔀 :: (#169) 구글 회원가입 / 로그인 상태 코드
  src/main/java/kr/hs/entrydsm/raisepercent/domain/teacher/service/GoogleAuthService.java
  src/test/java/kr/hs/entrydsm/raisepercent/domain/teacher/service/GoogleAuthServiceTest.java
Labels: 버그

#162 🔀 :: (#161) 공개 문서 조회 api
  src/main/java/kr/hs/entrydsm/raisepercent/domain/document/domain/repositories/PublicDocumentRepository.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/document/presentation/DocumentController.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/document/presentation/dto/response/QueryDocumentDetailsElement.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/document/presentation/dto/response/QueryDocumentDetailsResponse.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/document/service/QueryPublicDocumentDetailsService.java
  src/main/java/kr/hs/entrydsm/raisepercent/global/config/SecurityConfig.java
  src/test/java/kr/hs/entrydsm/raisepercent/domain/document/presentation/dto/response/QueryDocumentDetailsElementTest.java
  src/test/java/kr/hs/entrydsm/raisepercent/domain/document/presentation/dto/response/QueryDocumentDetailsResponseTest.java
  src/test/java/kr/hs/entrydsm/raisepercent/domain/document/service/QueryPublicDocumentDetailsServiceTest.java
Labels: 기능 추가

#176 🔀 :: (#173) 회사 등급 수정 API
  src/main/java/kr/hs/entrydsm/raisepercent/domain/company/domain/repositories/CompanyRepository.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/company/exception/CompanyNotFoundException.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/company/facade/CompanyFacade.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/company/presentation/CompanyController.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/company/service/ChangeRankService.java
  src/main/java/kr/hs/entrydsm/raisepercent/global/error/exception/ErrorCode.java
  src/test/java/kr/hs/entrydsm/raisepercent/domain/company/exception/CompanyNotFoundExceptionTest.java
  src/test/java/kr/hs/entrydsm/raisepercent/domain/company/facade/CompanyFacadeTest.java
  src/test/java/kr/hs/entrydsm/raisepercent/domain/company/service/ChangeRankServiceTest.java
Labels: 기능 추가
