Repository EntryDSM/Raise-Percent, pull requests merged in 2022-01, with the labels that each got.

#71 🔀 :: (#70) JwtTokenFilter 구현
  src/main/java/kr/hs/entrydsm/raisepercent/global/security/jwt/JwtTokenFilter.java
  src/test/java/kr/hs/entrydsm/raisepercent/global/security/jwt/JwtTokenFilterTest.java
Labels: 기능 추가

#77 🔀 :: (#72) 추가정보 입력 api
  src/main/java/kr/hs/entrydsm/raisepercent/domain/user/facade/UserFacade.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/user/presentation/UserController.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/user/presentation/dto/request/UpdateInformationRequest.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/user/service/UpdateInformationService.java
  src/main/java/kr/hs/entrydsm/raisepercent/global/error/exception/ErrorCode.java
  src/main/java/kr/hs/entrydsm/raisepercent/global/exception/CredentialsNotFoundException.java
  src/test/java/kr/hs/entrydsm/raisepercent/domain/user/facade/UserFacadeTest.java
  src/test/java/kr/hs/entrydsm/raisepercent/domain/user/service/UpdateInformationServiceTest.java
  src/test/java/kr/hs/entrydsm/raisepercent/global/exception/CredentialsNotFoundExceptionTest.java
Labels: 기능 추가

#76 🔀 :: (#75) Open Feign 설정
  build.gradle
  src/main/java/kr/hs/entrydsm/raisepercent/global/error/exception/ErrorCode.java
  src/main/java/kr/hs/entrydsm/raisepercent/infrastructure/feign/FeignClientErrorDecoder.java
  src/main/java/kr/hs/entrydsm/raisepercent/infrastructure/feign/FeignConfig.java
  src/main/java/kr/hs/entrydsm/raisepercent/infrastructure/feign/client/GoogleAuth.java
  src/main/java/kr/hs/entrydsm/raisepercent/infrastructure/feign/dto/request/GoogleCodeRequest.java
  src/main/java/kr/hs/entrydsm/raisepercent/infrastructure/feign/dto/response/TokenResponse.java
  src/main/java/kr/hs/entrydsm/raisepercent/infrastructure/feign/exception/OtherBadRequestException.java
  src/main/java/kr/hs/entrydsm/raisepercent/infrastructure/feign/exception/OtherExpiredTokenException.java
  src/main/java/kr/hs/entrydsm/raisepercent/infrastructure/feign/exception/OtherForbiddenException.java
  src/main/java/kr/hs/entrydsm/raisepercent/infrastructure/feign/exception/OtherUnAuthorizedException.java
  src/test/java/kr/hs/entrydsm/raisepercent/infrastructure/feign/dto/request/GoogleCodeRequestTest.java
  src/test/java/kr/hs/entrydsm/raisepercent/infrastructure/feign/exception/OtherBadRequestTest.java
  src/test/java/kr/hs/entrydsm/raisepercent/infrastructure/feign/exception/OtherExpiredTokenExceptionTest.java
  src/test/java/kr/hs/entrydsm/raisepercent/infrastructure/feign/exception/OtherForbiddenExceptionTest.java
  src/test/java/kr/hs/entrydsm/raisepercent/infrastructure/feign/exception/OtherUnAuthorizedExceptionTest.java
Labels: 기능 추가, 프로젝트 설정

#80 🔀 :: (#79) RefreshToken 인증
  src/main/java/kr/hs/entrydsm/raisepercent/global/security/jwt/JwtTokenProvider.java
  src/test/java/kr/hs/entrydsm/raisepercent/global/security/jwt/JwtTokenProviderTest.java
Labels: 버그

#82 🔀 :: (#74) 선생님 로그인 링크 가져오기
  src/main/java/kr/hs/entrydsm/raisepercent/domain/teacher/presentation/TeacherController.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/teacher/service/QueryGoogleAuthLinkService.java
  src/main/java/kr/hs/entrydsm/raisepercent/global/properties/AuthProperties.java
  src/main/java/kr/hs/entrydsm/raisepercent/global/properties/JwtProperties.java
  src/main/java/kr/hs/entrydsm/raisepercent/global/security/jwt/JwtTokenProvider.java
  src/main/resources/application.yml
  src/test/java/kr/hs/entrydsm/raisepercent/domain/teacher/service/QueryGoogleAuthLinkServiceTest.java
  src/test/java/kr/hs/entrydsm/raisepercent/global/properties/AuthPropertiesTest.java
  src/test/java/kr/hs/entrydsm/raisepercent/global/properties/JwtPropertiesTest.java
  src/test/java/kr/hs/entrydsm/raisepercent/global/security/jwt/JwtTokenProviderTest.java
Labels: 기능 추가

#83 🔀 :: (#78) Redis 연결 설정
  src/main/java/kr/hs/entrydsm/raisepercent/global/config/RedisConfig.java
Labels: 프로젝트 설정

#91 🔀 :: (#90) 버전 수정
  build.gradle
Labels: 버그, 프로젝트 설정

#88 🔀 :: (#87) 디바이스 토큰 입력 api
  src/main/java/kr/hs/entrydsm/raisepercent/domain/user/exception/InvalidTypeException.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/user/presentation/UserController.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/user/presentation/dto/request/UpdateDeviceTokenRequest.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/user/service/UpdateDeviceTokenService.java
  src/main/java/kr/hs/entrydsm/raisepercent/global/error/exception/ErrorCode.java
  src/test/java/kr/hs/entrydsm/raisepercent/domain/user/exception/InvalidTypeExceptionTest.java
  src/test/java/kr/hs/entrydsm/raisepercent/domain/user/service/UpdateDeviceTokenServiceTest.java
Labels: 기능 추가

#84 🔀 :: (#12) 피드백 작성 api
  src/main/java/kr/hs/entrydsm/raisepercent/domain/document/facade/DocumentFacade.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/feedback/domain/Feedback.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/feedback/presentation/FeedbackController.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/feedback/presentation/dto/request/CreateFeedbackRequest.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/feedback/service/CreateFeedbackService.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/teacher/facade/TeacherFacade.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/user/facade/UserFacade.java
  src/main/java/kr/hs/entrydsm/raisepercent/global/config/SecurityConfig.java
  src/main/java/kr/hs/entrydsm/raisepercent/global/error/exception/ErrorCode.java
  src/main/java/kr/hs/entrydsm/raisepercent/global/exception/DocumentNotFoundException.java
  src/main/java/kr/hs/entrydsm/raisepercent/global/exception/InvalidRoleException.java
  src/main/java/kr/hs/entrydsm/raisepercent/global/facade/AuthFacade.java
  src/test/java/kr/hs/entrydsm/raisepercent/domain/document/facade/DocumentFacadeTest.java
  src/test/java/kr/hs/entrydsm/raisepercent/domain/feedback/service/CreateFeedbackServiceTest.java
  src/test/java/kr/hs/entrydsm/raisepercent/domain/teacher/facade/TeacherFacadeTest.java
  src/test/java/kr/hs/entrydsm/raisepercent/domain/user/facade/UserFacadeTest.java
  src/test/java/kr/hs/entrydsm/raisepercent/global/exception/DocumentNotFoundExceptionTest.java
  src/test/java/kr/hs/entrydsm/raisepercent/global/exception/InvalidRoleExceptionTest.java
Labels: 기능 추가

#96 🔀 :: (#86) 선생님 로그인 / 회원가입
  src/main/java/kr/hs/entrydsm/raisepercent/domain/teacher/presentation/TeacherController.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/teacher/service/GoogleAuthService.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/teacher/service/QueryGoogleAuthLinkService.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/user/presentation/dto/request/CodeRequest.java
  src/main/java/kr/hs/entrydsm/raisepercent/global/config/SecurityConfig.java
  src/main/java/kr/hs/entrydsm/raisepercent/global/security/jwt/dto/TokenResponse.java
  src/main/java/kr/hs/entrydsm/raisepercent/infrastructure/feign/client/GoogleInfo.java
  src/main/java/kr/hs/entrydsm/raisepercent/infrastructure/feign/dto/response/GoogleInfoResponse.java
  src/test/java/kr/hs/entrydsm/raisepercent/domain/teacher/service/GoogleAuthServiceTest.java
  src/test/java/kr/hs/entrydsm/raisepercent/domain/teacher/service/QueryGoogleAuthLinkServiceTest.java
  src/test/java/kr/hs/entrydsm/raisepercent/global/security/jwt/dto/TokenResponseTest.java
Labels: 기능 추가

#98 🔀 :: (#95) 선생님 인증 코드 발급
  src/main/java/kr/hs/entrydsm/raisepercent/domain/code/facade/CodeAlreadyExistsException.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/code/facade/CodeFacade.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/code/service/CodeIssueService.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/teacher/presentation/TeacherController.java
  src/main/java/kr/hs/entrydsm/raisepercent/global/config/SecurityConfig.java
  src/main/java/kr/hs/entrydsm/raisepercent/global/error/exception/ErrorCode.java
  src/test/java/kr/hs/entrydsm/raisepercent/domain/code/exception/CodeAlreadyExistsExceptionTest.java
  src/test/java/kr/hs/entrydsm/raisepercent/domain/code/facade/CodeFacadeTest.java
  src/test/java/kr/hs/entrydsm/raisepercent/domain/code/service/CodeIssueServiceTest.java
Labels: 기능 추가

#101 🔀 :: (#92) 학생 프로필 가져오기 api
  src/main/java/kr/hs/entrydsm/raisepercent/domain/student/facade/StudentFacade.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/student/presentation/StudentController.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/student/presentation/dto/response/ProfileResponse.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/student/service/QueryStudentProfileService.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/tag/domain/repositories/RegisteredTagRepository.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/tag/facade/TagFacade.java
  src/main/java/kr/hs/entrydsm/raisepercent/global/config/SecurityConfig.java
  src/test/java/kr/hs/entrydsm/raisepercent/domain/student/facade/StudentFacadeTest.java
  src/test/java/kr/hs/entrydsm/raisepercent/domain/student/presentation/dto/response/ProfileResponseTest.java
  src/test/java/kr/hs/entrydsm/raisepercent/domain/student/service/QueryStudentProfileServiceTest.java
  src/test/java/kr/hs/entrydsm/raisepercent/domain/tag/facade/TagFacadeTest.java
Labels: 기능 추가

#102 🔀 :: (#100) 코드 발급 예외 테스트
  src/main/java/kr/hs/entrydsm/raisepercent/domain/code/facade/CodeAlreadyExistsException.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/code/facade/CodeFacade.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/code/service/CodeIssueService.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/teacher/presentation/TeacherController.java
  src/main/java/kr/hs/entrydsm/raisepercent/global/config/SecurityConfig.java
  src/main/java/kr/hs/entrydsm/raisepercent/global/error/exception/ErrorCode.java
  src/main/java/kr/hs/entrydsm/raisepercent/global/exception/CodeNotFoundException.java
  src/test/java/kr/hs/entrydsm/raisepercent/domain/code/exception/CodeAlreadyExistsExceptionTest.java
  src/test/java/kr/hs/entrydsm/raisepercent/domain/code/facade/CodeFacadeTest.java
  src/test/java/kr/hs/entrydsm/raisepercent/domain/code/service/CodeIssueServiceTest.java
  src/test/java/kr/hs/entrydsm/raisepercent/global/exception/CodeNotFoundExceptionTest.java
Labels: 기능 추가

#104 🔀 :: (#103) 테스트코드 통일
  src/test/java/kr/hs/entrydsm/raisepercent/domain/document/dto/CreateDocumentResponseTest.java
  src/test/java/kr/hs/entrydsm/raisepercent/domain/document/service/CreateDocumentServiceTest.java
  src/test/java/kr/hs/entrydsm/raisepercent/domain/feedback/service/CreateFeedbackServiceTest.java
  src/test/java/kr/hs/entrydsm/raisepercent/domain/user/facade/UserFacadeTest.java
  src/test/java/kr/hs/entrydsm/raisepercent/domain/user/service/UpdateInformationServiceTest.java
  src/test/java/kr/hs/entrydsm/raisepercent/global/properties/JwtPropertiesTest.java
Labels: 리팩토링

#106 🔀 :: (#99) 선생님 인증코드 재발급
  src/main/java/kr/hs/entrydsm/raisepercent/domain/code/domain/Code.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/code/service/CodeReissueService.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/code/service/QueryCodeService.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/teacher/presentation/TeacherController.java
  src/main/java/kr/hs/entrydsm/raisepercent/global/config/SecurityConfig.java
  src/main/resources/application.yml
  src/test/java/kr/hs/entrydsm/raisepercent/domain/code/service/CodeReissueServiceTest.java
  src/test/java/kr/hs/entrydsm/raisepercent/domain/code/service/QueryCodeServiceTest.java
Labels: 기능 추가

#111 🔀 :: (#109) Open Feign 에러 디코딩 테스트
  src/test/java/kr/hs/entrydsm/raisepercent/infrastructure/feign/FeignClientErrorDecoderTest.java
Labels: 기능 추가

#110 🔀 :: (#93) 태그 등록하기 api
  src/main/java/kr/hs/entrydsm/raisepercent/domain/student/presentation/StudentController.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/student/presentation/dto/request/RegisterTagRequest.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/student/service/RegisterTagService.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/tag/domain/RegisteredTag.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/tag/domain/repositories/RegisteredTagRepository.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/tag/domain/repositories/TagRepository.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/tag/exception/AlreadyRegisteredTagException.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/tag/exception/TagNotFoundException.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/tag/facade/TagFacade.java
  src/main/java/kr/hs/entrydsm/raisepercent/global/error/exception/ErrorCode.java
  src/test/java/kr/hs/entrydsm/raisepercent/domain/student/service/RegisterTagServiceTest.java
  src/test/java/kr/hs/entrydsm/raisepercent/domain/tag/exception/AlreadyRegisteredTagExceptionTest.java
  src/test/java/kr/hs/entrydsm/raisepercent/domain/tag/exception/TagNotFoundExceptionTest.java
  src/test/java/kr/hs/entrydsm/raisepercent/domain/tag/facade/TagFacadeTest.java
Labels: 기능 추가

#108 🔀 :: (#85) show feedback
  src/main/java/kr/hs/entrydsm/raisepercent/domain/feedback/domain/repositories/FeedbackRepository.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/feedback/facade/FeedbackFacade.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/feedback/presentation/FeedbackController.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/feedback/presentation/dto/response/ShowFeedbackResponse.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/feedback/service/ShowFeedbackService.java
  src/main/java/kr/hs/entrydsm/raisepercent/global/config/SecurityConfig.java
  src/main/java/kr/hs/entrydsm/raisepercent/global/entity/BaseDocumentContentEntity.java
  src/main/java/kr/hs/entrydsm/raisepercent/global/error/exception/ErrorCode.java
  src/main/java/kr/hs/entrydsm/raisepercent/global/exception/FeedbackNotFoundException.java
  src/main/java/kr/hs/entrydsm/raisepercent/global/security/auth/AuthDetails.java
  src/test/java/kr/hs/entrydsm/raisepercent/domain/feedback/facade/FeedbackFacadeTest.java
  src/test/java/kr/hs/entrydsm/raisepercent/domain/feedback/service/ShowFeedbackServiceTest.java
  src/test/java/kr/hs/entrydsm/raisepercent/global/exception/FeedbackNotFoundExceptionTest.java
Labels: 기능 추가

#116 🔀 :: (#115) 선생님 로그인 / 회원가입 Response Status
  src/main/java/kr/hs/entrydsm/raisepercent/domain/teacher/presentation/TeacherController.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/teacher/service/GoogleAuthService.java
  src/test/java/kr/hs/entrydsm/raisepercent/domain/teacher/service/GoogleAuthServiceTest.java
Labels: 버그

#113 🔀 :: (#112) 알림목록 Api (/users/notification)
  src/main/java/kr/hs/entrydsm/raisepercent/domain/notification/domain/facade/NotificationFacade.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/notification/domain/repositories/NotificationRepository.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/user/presentation/UserController.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/user/presentation/dto/response/NotificationElement.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/user/presentation/dto/response/NotificationListResponse.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/user/service/QueryNotificationListService.java
  src/test/java/kr/hs/entrydsm/raisepercent/domain/notification/domain/facade/NotificationFacadeTest.java
  src/test/java/kr/hs/entrydsm/raisepercent/domain/user/presentation/dto/response/NotificationElementTest.java
  src/test/java/kr/hs/entrydsm/raisepercent/domain/user/presentation/dto/response/NotificationListResponseTest.java
  src/test/java/kr/hs/entrydsm/raisepercent/domain/user/service/QueryNotificationListServiceTest.java
Labels: 기능 추가

#114 🔀 :: (#107) 선생님 인증
  src/main/java/kr/hs/entrydsm/raisepercent/domain/teacher/code/domain/Code.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/teacher/code/domain/repositories/CodeRepository.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/teacher/code/exception/CodeNotFoundException.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/teacher/code/exception/CodeNotMatchException.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/teacher/code/facade/CodeFacade.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/teacher/code/presentation/CodeController.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/teacher/code/presentation/dto/request/VerifyTeacherRequest.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/teacher/code/service/CodeReissueService.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/teacher/code/service/CodeVerificationService.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/teacher/code/service/QueryCodeService.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/teacher/presentation/TeacherController.java
  src/main/java/kr/hs/entrydsm/raisepercent/global/config/SecurityConfig.java
  src/main/java/kr/hs/entrydsm/raisepercent/global/error/exception/ErrorCode.java
  src/test/java/kr/hs/entrydsm/raisepercent/domain/teacher/code/domain/CodeTest.java
  src/test/java/kr/hs/entrydsm/raisepercent/domain/teacher/code/exception/CodeNotFoundExceptionTest.java
  src/test/java/kr/hs/entrydsm/raisepercent/domain/teacher/code/exception/CodeNotMatchExceptionTest.java
  src/test/java/kr/hs/entrydsm/raisepercent/domain/teacher/code/facade/CodeFacadeTest.java
  src/test/java/kr/hs/entrydsm/raisepercent/domain/teacher/code/service/CodeReissueServiceTest.java
  src/test/java/kr/hs/entrydsm/raisepercent/domain/teacher/code/service/CodeVerificationServiceTest.java
  src/test/java/kr/hs/entrydsm/raisepercent/domain/teacher/code/service/QueryCodeServiceTest.java
Labels: 기능 추가, 리팩토링

#118 🔀 :: (#117) 분야 수정하기 (/students/position)
  src/main/java/kr/hs/entrydsm/raisepercent/domain/student/domain/Student.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/student/domain/types/Position.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/student/presentation/StudentController.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/student/presentation/dto/request/UpdatePositionRequest.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/student/service/QueryStudentProfileService.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/student/service/UpdatePositionService.java
  src/main/java/kr/hs/entrydsm/raisepercent/global/config/SecurityConfig.java
  src/main/java/kr/hs/entrydsm/raisepercent/global/error/exception/ErrorCode.java
  src/main/java/kr/hs/entrydsm/raisepercent/global/exception/InvalidEnumValueException.java
  src/main/java/kr/hs/entrydsm/raisepercent/global/util/EnumUtil.java
  src/test/java/kr/hs/entrydsm/raisepercent/domain/student/domain/StudentTest.java
  src/test/java/kr/hs/entrydsm/raisepercent/domain/student/service/QueryStudentProfileServiceTest.java
  src/test/java/kr/hs/entrydsm/raisepercent/domain/student/service/UpdatePositionServiceTest.java
  src/test/java/kr/hs/entrydsm/raisepercent/global/exception/InvalidEnumValueExceptionTest.java
  src/test/java/kr/hs/entrydsm/raisepercent/global/util/EnumUtilTest.java
Labels: 기능 추가

#122 🔀 :: (#119) 알림 확인 (/users/notifications/{notification-id})
  src/main/java/kr/hs/entrydsm/raisepercent/domain/notification/domain/Notification.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/notification/domain/exception/NotYourNotificationException.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/notification/domain/exception/NotificationNotFoundException.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/user/presentation/UserController.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/user/service/CheckNotificationService.java
  src/main/java/kr/hs/entrydsm/raisepercent/global/error/exception/ErrorCode.java
  src/test/java/kr/hs/entrydsm/raisepercent/domain/notification/domain/NotificationTest.java
  src/test/java/kr/hs/entrydsm/raisepercent/domain/notification/domain/exception/NotYourNotificationExceptionTest.java
  src/test/java/kr/hs/entrydsm/raisepercent/domain/notification/domain/exception/NotificationNotFoundExceptionTest.java
  src/test/java/kr/hs/entrydsm/raisepercent/domain/user/service/CheckNotificationServiceTest.java
Labels: 기능 추가

#124 🔀 :: (#120) UUID util
  src/main/java/kr/hs/entrydsm/raisepercent/domain/tag/facade/TagFacade.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/user/service/CheckNotificationService.java
  src/main/java/kr/hs/entrydsm/raisepercent/global/error/exception/ErrorCode.java
  src/main/java/kr/hs/entrydsm/raisepercent/global/exception/InvalidUUIDValueException.java
  src/main/java/kr/hs/entrydsm/raisepercent/global/util/UUIDUtil.java
  src/test/java/kr/hs/entrydsm/raisepercent/global/exception/InvalidUUIDValueExceptionTest.java
  src/test/java/kr/hs/entrydsm/raisepercent/global/util/UUIDUtilTest.java
Labels: 기능 추가

#127 🔀 :: (#126) 북마크한 회사 보기 Api
  src/main/java/kr/hs/entrydsm/raisepercent/domain/bookmark/domain/Bookmark.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/bookmark/domain/repositories/BookmarkRepository.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/student/presentation/StudentController.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/student/presentation/dto/response/BookmarkElement.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/student/presentation/dto/response/BookmarkListResponse.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/student/service/QueryBookmarkService.java
  src/main/java/kr/hs/entrydsm/raisepercent/global/config/SecurityConfig.java
  src/test/java/kr/hs/entrydsm/raisepercent/domain/student/presentation/dto/response/BookmarkElementTest.java
  src/test/java/kr/hs/entrydsm/raisepercent/domain/student/presentation/dto/response/BookmarkListResponseTest.java
  src/test/java/kr/hs/entrydsm/raisepercent/domain/student/service/QueryBookmarkServiceTest.java
Labels: 기능 추가

#125 🔀 :: (#123) 피드백 수정
  src/main/java/kr/hs/entrydsm/raisepercent/domain/feedback/facade/FeedbackFacade.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/feedback/presentation/FeedbackController.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/feedback/presentation/dto/request/UpdateFeedbackRequest.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/feedback/service/CreateFeedbackService.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/feedback/service/ShowFeedbackService.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/feedback/service/UpdateFeedbackService.java
  src/main/java/kr/hs/entrydsm/raisepercent/global/config/SecurityConfig.java
  src/test/java/kr/hs/entrydsm/raisepercent/domain/feedback/service/CreateFeedbackServiceTest.java
  src/test/java/kr/hs/entrydsm/raisepercent/domain/feedback/service/ShowFeedbackServiceTest.java
  src/test/java/kr/hs/entrydsm/raisepercent/domain/feedback/service/UpdateFeedbackServiceTest.java
Labels: 기능 추가

#128 🔀 :: (#121) 공지사항 등록
  src/main/java/kr/hs/entrydsm/raisepercent/domain/notice/presentation/NoticeController.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/notice/presentation/dto/request/RegistrationNoticeRequest.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/notice/service/RegistrationNoticeService.java
  src/main/java/kr/hs/entrydsm/raisepercent/global/config/SecurityConfig.java
  src/test/java/kr/hs/entrydsm/raisepercent/domain/notice/service/RegistrationNoticeServiceTest.java
Labels: 기능 추가

#130 🔀 :: (#129) Request dto Length 설정
  src/main/java/kr/hs/entrydsm/raisepercent/domain/user/presentation/dto/request/UpdateDeviceTokenRequest.java
Labels: 기능 추가

#135 🔀 :: (#134) 제출한 문서 리스트
  src/main/java/kr/hs/entrydsm/raisepercent/domain/document/domain/SubmittedDocument.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/document/domain/repositories/SubmittedDocumentRepository.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/document/facade/DocumentFacade.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/document/presentation/DocumentController.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/document/presentation/dto/response/SubmittedDocumentElement.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/document/presentation/dto/response/SubmittedDocumentListResponse.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/document/service/QuerySubmittedDocumentListService.java
  src/main/java/kr/hs/entrydsm/raisepercent/global/config/SecurityConfig.java
  src/test/java/kr/hs/entrydsm/raisepercent/domain/document/domain/DocumentUserConstant.java
  src/test/java/kr/hs/entrydsm/raisepercent/domain/document/facade/DocumentFacadeTest.java
  src/test/java/kr/hs/entrydsm/raisepercent/domain/document/presentation/dto/response/CreateDocumentResponseTest.java
  src/test/java/kr/hs/entrydsm/raisepercent/domain/document/presentation/dto/response/SubmittedDocumentElementTest.java
  src/test/java/kr/hs/entrydsm/raisepercent/domain/document/presentation/dto/response/SubmittedDocumentListResponseTest.java
  src/test/java/kr/hs/entrydsm/raisepercent/domain/document/service/QuerySubmittedDocumentListServiceTest.java
Labels: 기능 추가

#136 🔀 :: (#132) 피드백 삭제
  src/main/java/kr/hs/entrydsm/raisepercent/domain/feedback/presentation/FeedbackController.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/feedback/service/DeleteFeedbackService.java
  src/main/java/kr/hs/entrydsm/raisepercent/global/config/SecurityConfig.java
  src/test/java/kr/hs/entrydsm/raisepercent/domain/feedback/service/DeleteFeedbackServiceTest.java
  src/test/java/kr/hs/entrydsm/raisepercent/domain/teacher/facade/TeacherFacadeTest.java
Labels: chore, 기능 추가

#141 🐛 :: column 명
  src/main/java/kr/hs/entrydsm/raisepercent/domain/company/domain/Company.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/hr/domain/Hr.java
  src/test/java/kr/hs/entrydsm/raisepercent/domain/company/domain/CompanyTest.java
  src/test/java/kr/hs/entrydsm/raisepercent/domain/hr/domain/HrTest.java
  src/test/java/kr/hs/entrydsm/raisepercent/global/facade/AuthFacadeTest.java
Labels: 버그

#139 🔀 :: (#138) 태그 목록
  src/main/java/kr/hs/entrydsm/raisepercent/domain/tag/domain/repositories/TagRepository.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/tag/presentation/TagController.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/tag/presentation/dto/response/ShowTagListResponse.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/tag/presentation/dto/response/TagListResponse.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/tag/service/ShowTagListService.java
  src/test/java/kr/hs/entrydsm/raisepercent/domain/tag/service/ShowTagListServiceTest.java
Labels: 기능 추가

#142 🔀 :: (#140) notice list
  src/main/java/kr/hs/entrydsm/raisepercent/domain/notice/domain/repositories/NoticeRepository.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/notice/presentation/NoticeController.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/notice/presentation/dto/response/NoticeListResponse.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/notice/presentation/dto/response/NoticeResponse.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/notice/service/NoticeListService.java
  src/test/java/kr/hs/entrydsm/raisepercent/domain/notice/service/NoticeListServiceTest.java
Labels: 기능 추가

#145 🔀 :: (#137) 제출한 문서 승인
  src/main/java/kr/hs/entrydsm/raisepercent/domain/document/domain/repositories/PublicDocumentRepository.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/document/domain/repositories/StayDocumentRepository.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/document/presentation/DocumentController.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/document/service/ApproveStayDocumentService.java
  src/test/java/kr/hs/entrydsm/raisepercent/domain/document/service/ApproveStayDocumentServiceTest.java
Labels: 기능 추가
