Repository EntryDSM/Raise-Percent, pull requests merged in 2022-03, with the labels that each got.

#178 🔀 :: (#177) 공지 사항 내용 변경
  src/main/java/kr/hs/entrydsm/raisepercent/domain/notice/domain/Notice.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/notice/facade/NoticeFacade.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/notice/presentation/NoticeController.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/notice/presentation/dto/request/UpdateNoticeRequest.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/notice/service/UpdateNoticeService.java
  src/test/java/kr/hs/entrydsm/raisepercent/domain/notice/facade/NoticeFacadeTest.java
  src/test/java/kr/hs/entrydsm/raisepercent/domain/notice/service/UpdateNoticeServiceTest.java
Labels: 기능 추가

#182 🔀 :: (#179) 로그인 링크 가져오기 Api
  src/main/java/kr/hs/entrydsm/raisepercent/domain/student/presentation/StudentController.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/student/presentation/dto/response/UserAuthLinkResponse.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/student/service/QueryUserAuthLinkService.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/user/presentation/UserController.java
  src/main/java/kr/hs/entrydsm/raisepercent/global/properties/DsmAuthProperties.java
  src/test/java/kr/hs/entrydsm/raisepercent/domain/user/presentation/dto/response/UserAuthLinkResponseTest.java
  src/test/java/kr/hs/entrydsm/raisepercent/domain/user/service/QueryUserAuthLinkServiceTest.java
  src/test/java/kr/hs/entrydsm/raisepercent/global/properties/DsmAuthPropertiesTest.java
Labels: 기능 추가

#184 🔀 :: (#148) global 테스트코드 리팩토링
  src/test/java/kr/hs/entrydsm/raisepercent/global/entity/BaseDocumentContentEntityTest.java
  src/test/java/kr/hs/entrydsm/raisepercent/global/entity/DocumentContentIdTest.java
  src/test/java/kr/hs/entrydsm/raisepercent/global/error/ErrorResponseTest.java
  src/test/java/kr/hs/entrydsm/raisepercent/global/error/ExceptionHandlingFilterTest.java
  src/test/java/kr/hs/entrydsm/raisepercent/global/error/exception/RaiseExceptionTest.java
  src/test/java/kr/hs/entrydsm/raisepercent/global/facade/AuthFacadeTest.java
  src/test/java/kr/hs/entrydsm/raisepercent/global/properties/AuthPropertiesTest.java
  src/test/java/kr/hs/entrydsm/raisepercent/global/properties/JwtPropertiesTest.java
  src/test/java/kr/hs/entrydsm/raisepercent/global/security/auth/AuthDetailsServiceTest.java
  src/test/java/kr/hs/entrydsm/raisepercent/global/security/auth/AuthDetailsTest.java
  src/test/java/kr/hs/entrydsm/raisepercent/global/security/jwt/JwtTokenFilterTest.java
  src/test/java/kr/hs/entrydsm/raisepercent/global/security/jwt/JwtTokenProviderTest.java
  src/test/java/kr/hs/entrydsm/raisepercent/global/security/jwt/dto/TokenResponseTest.java
  src/test/java/kr/hs/entrydsm/raisepercent/infrastructure/feign/FeignClientErrorDecoderTest.java
  src/test/java/kr/hs/entrydsm/raisepercent/infrastructure/feign/dto/request/GoogleCodeRequestTest.java
Labels: 리팩토링

#190 🔀 :: (#189) 토큰 재발급 Api
  src/main/java/kr/hs/entrydsm/raisepercent/domain/user/domain/repositories/RefreshTokenRepository.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/user/presentation/UserController.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/user/service/UserRefreshTokenService.java
  src/main/java/kr/hs/entrydsm/raisepercent/global/error/exception/ErrorCode.java
  src/main/java/kr/hs/entrydsm/raisepercent/global/security/jwt/JwtTokenProvider.java
  src/test/java/kr/hs/entrydsm/raisepercent/domain/user/service/UserRefreshTokenServiceTest.java
  src/test/java/kr/hs/entrydsm/raisepercent/global/security/jwt/JwtTokenProviderTest.java
Labels: chore, 기능 추가

#183 🔀 :: (#180) 로그인 / 회원가입 Api
  src/main/java/kr/hs/entrydsm/raisepercent/domain/student/presentation/StudentController.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/student/presentation/dto/request/CodeRequest.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/student/presentation/dto/response/TokenResponse.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/student/service/StudentAuthService.java
  src/main/java/kr/hs/entrydsm/raisepercent/global/properties/DsmAuthProperties.java
  src/main/java/kr/hs/entrydsm/raisepercent/infrastructure/feign/client/DsmAuth.java
  src/main/java/kr/hs/entrydsm/raisepercent/infrastructure/feign/dto/request/DsmAuthTokenRequest.java
  src/main/java/kr/hs/entrydsm/raisepercent/infrastructure/feign/dto/response/DsmAuthTokenResponse.java
  src/main/java/kr/hs/entrydsm/raisepercent/infrastructure/feign/dto/response/InformationResponse.java
  src/main/resources/application.yml
Labels: 기능 추가

#192 🔀 :: (#191) Codecov 설정
  codecov.yml
Labels: 프로젝트 설정

#194 🔀 :: (#193) 학생 로그인 오류
  src/main/java/kr/hs/entrydsm/raisepercent/domain/student/service/QueryUserAuthLinkService.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/student/service/StudentAuthService.java
  src/main/java/kr/hs/entrydsm/raisepercent/global/config/SecurityConfig.java
  src/main/java/kr/hs/entrydsm/raisepercent/global/properties/DsmAuthProperties.java
  src/main/resources/application.yml
  src/test/java/kr/hs/entrydsm/raisepercent/domain/user/service/QueryUserAuthLinkServiceTest.java
  src/test/java/kr/hs/entrydsm/raisepercent/global/properties/DsmAuthPropertiesTest.java
Labels: 버그

#186 🔀 :: (#186) 공지사항 삭제 API
  src/main/java/kr/hs/entrydsm/raisepercent/domain/notice/presentation/NoticeController.java
  src/main/java/kr/hs/entrydsm/raisepercent/domain/notice/service/DeleteNoticeService.java
  src/main/java/kr/hs/entrydsm/raisepercent/global/config/SecurityConfig.java
  src/test/java/kr/hs/entrydsm/raisepercent/domain/notice/service/DeleteNoticeServiceTest.java
Labels: 기능 추가

#197 🔀 :: (#196) ErrorResponse toString
  src/main/java/kr/hs/entrydsm/raisepercent/global/error/ErrorResponse.java
Labels: chore
